version: '3'
services:
  db:
    image: postgres:11
    volumes:
      - ./db/db-create.sh:/docker-entrypoint-initdb.d/create-db.sh
      - rails-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/band-name-generator
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  rails-data:
