default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mybanderoo_development
  host: db
  password:
  pool: 5
  username: postgres

test:
  <<: *default
  database: mybanderoo_test
  host: db
  password:
  pool: 5
  username: postgres

production:
  <<: *default
