development:
  adapter: postgresql
  encoding: unicode
  database: mybanderoo_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: mybanderoo_test
  pool: 5
  username: 
  password: 